# Generated by Django 4.2.11 on 2024-07-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
