# Generated by Django 4.2.11 on 2024-07-09 12:51

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='blog.blog'),
        ),
    ]
