# Generated by Django 4.2.11 on 2024-04-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('VG', 'Vegetables'), ('FR', 'Fruits'), ('DR', 'Drinks'), ('MT', 'Meats')], max_length=25)),
            ],
        ),
    ]
