# Generated by Django 4.2.11 on 2024-04-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VG', 'Vegetables'), ('FR', 'Fruits'), ('DR', 'Drinks'), ('MT', 'Meats'), ('FD', 'Fastfood')], max_length=25),
        ),
    ]
