# Generated by Django 4.2.11 on 2024-04-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VG', 'Vegetables'), ('FR', 'Fruits'), ('DR', 'Drinks'), ('MT', 'Meats'), ('FD', 'Fastfood'), ('JC', 'juice')], max_length=25),
        ),
    ]
