# Generated by Django 4.2.11 on 2024-04-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VG', 'Vegetables'), ('FR', 'Fruits'), ('MT', 'Meats'), ('FD', 'Fastfood'), ('JC', 'juice')], max_length=25),
        ),
    ]
