# Generated by Django 4.2.11 on 2024-04-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Meats', 'Meats'), ('Fastfood', 'Fastfood'), ('Juice', 'Juice')], max_length=25),
        ),
    ]
