# Generated by Django 4.2.11 on 2024-05-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_slug'),
        ('accounts', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
