# Generated by Django 4.2.11 on 2024-09-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='full_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zip',
            field=models.CharField(max_length=15),
        ),
    ]
