# Generated by Django 4.2.11 on 2024-05-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_checkout_check_payment_checkout_paypal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='check_Payment',
            new_name='check_payment',
        ),
    ]
