# Generated by Django 4.2.11 on 2024-05-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_check_payment_checkout_check_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zip',
            field=models.CharField(max_length=15),
        ),
    ]
